### ISSUE TITLE
Install is performing a fuzzy match

### ISSUE THREAD

**Issue by brendanstephens** [pivotal-gss/go-gpdb#7] opened 2019-01-11 15:46 UTC
gpdb install -v 4.3.30. or 4.3 will simply pick the latest binary in the downloads directory, then install it, but with an incomplete name: eg:  `env_4.3.30._20181214175506`

**Comment by faisaltheparttimecoder** [comment] 2019-04-19 14:41
@Zerpet is working on this, this is a duplicate of https://github.com/pivotal-gss/go-gpdb/issues/15, so closing this one

**Comment by faisaltheparttimecoder** [comment] 2019-04-19 14:45
added into master via: https://github.com/pivotal-gss/go-gpdb/commit/cfd6629ad00eb31b4d4ef10bc699c017191d00dd

**Closed by faisaltheparttimecoder** 2019-04-19 14:45 UTC
